In [15]:
!git rm --cached deep-learning-v2-pytorch

error: the following file has staged content different from both the
file and the HEAD:
    deep-learning-v2-pytorch
(use -f to force removal)


# Some Basics

In [161]:
!pip show pandas
!pip show numpy

Name: pandas
Version: 1.0.5
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: https://pandas.pydata.org
Author: None
Author-email: None
License: BSD
Location: c:\users\raul\appdata\local\programs\python\python38-32\lib\site-packages
Requires: pytz, python-dateutil, numpy
Required-by: 
Name: numpy
Version: 1.19.0
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: None
License: BSD
Location: c:\users\raul\appdata\local\programs\python\python38-32\lib\site-packages
Requires: 
Required-by: pandas


In [162]:
import numpy as np
import pandas as pd

In [163]:
a = np.array([1,2,3], dtype= 'int16')
a

array([1, 2, 3], dtype=int16)

In [164]:
b = np.array([[9, 8, 7],[6, 5, 4]])
print(b)

[[9 8 7]
 [6 5 4]]


In [165]:
b.ndim

2

In [166]:
b.shape

(2, 3)

In [167]:
a.dtype

dtype('int16')

In [168]:
a.itemsize

2

In [169]:
a.size

3

In [170]:
a.nbytes

6

## Commands of interest

In [171]:
a = np.array([[1, 2, 3, 4, 5, 6, 7],[8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [172]:
a[1, 5]

13

In [173]:
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [174]:
# The step goes last
a[0,1:6:2]

array([2, 4, 6])

In [175]:
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [176]:
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [177]:
# 3-D arrays (work outside in)
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [178]:
b[0,1,1]

4

In [179]:
b[0,0,:]

array([1, 2])

In [180]:
c = np.zeros((1,2))
print(c)

d = np.full((2,2),99)
print(d)

[[0. 0.]]
[[99 99]
 [99 99]]


#### Copying an array

In [181]:
# Option 1
np.full_like(a, 7)

array([[7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7]])

In [182]:
# Option 2
np.full(a.shape,7)

array([[7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7]])

In [183]:
np.random.rand(4,2)

array([[6.76776167e-04, 7.99580181e-01],
       [7.94300809e-01, 5.02890773e-01],
       [8.04912995e-01, 4.38004205e-01],
       [8.33646933e-01, 9.96138780e-01]])

In [184]:
np.random.randint(7, size=(3,3))

array([[3, 5, 3],
       [2, 6, 6],
       [2, 3, 2]])

In [185]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [186]:
# Note how you need to make two-dimensional for it to work

# This won't work
arr = np.array([1,2,3])
r1 = np.repeat(arr,3,axis=0)
print(r1)

# This will
arr = np.array([[1,2,3]])
r2 = np.repeat(arr,3,axis=0)
print(r2)

# (We are trying to get the same row three times, btw)

[1 1 1 2 2 2 3 3 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [187]:
output = np.ones((5,5,))
print(output)

z = np.zeros((3,3))
z[1,1] = 9 
print(z)

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!

In [188]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(a)
# Note how 'a' has changed by changing 'b'

[100   2   3]


###### Classic problem with mutable/inmutable objects

In [189]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)

[1 2 3]


###### Solved

## Mathematics

In [190]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [191]:
a + 2

array([3, 4, 5, 6])

In [192]:
a - 2

array([-1,  0,  1,  2])

In [193]:
a * 2

array([2, 4, 6, 8])

In [194]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [195]:
b = np.array([1,0,1,0])
a + b 

array([2, 2, 4, 4])

In [196]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [197]:
# Take the sin 
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

##### Linear Algebra

In [198]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [199]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [200]:
c = np.identity(3)
np.linalg.det(c)

1.0

### Statistics

In [201]:
stats = np.array(([1,2,3],[4,5,6]))
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [202]:
np.min(stats)

1

In [203]:
np.max(stats, axis = 1)

array([3, 6])

In [204]:
np.sum(stats, axis = 0)

array([5, 7, 9])

### Reorganizing Arrays

In [205]:
before = np.array(([1,2,3,4],[5,6,7,8]))
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [206]:
after = before.reshape((2,2,2))
print(after)
# Will always work if both matrices have the same number of elements

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [207]:
# Vertically stacking vectors 
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

np.vstack([v1, v2, v1, v2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [208]:
# Horizontal stacking vectors 
h1 = np.full([2,4],1)
h2 = np.full([2,2],2)

np.hstack([h1, h2])

array([[1, 1, 1, 1, 2, 2],
       [1, 1, 1, 1, 2, 2]])

## Miscellaneous

### Loading data

In [209]:
filedata = np.genfromtxt('data.txt',delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[   1  234 2434   12   12]
 [   1  354 2323   13    8]
 [  10   34   11 1212    5]
 [   0    0  122  222    1]]


#### Boolean Masking and Advanced Indexing

In [210]:
filedata > 20

array([[False,  True,  True, False, False],
       [False,  True,  True, False, False],
       [False,  True, False,  True, False],
       [False, False,  True,  True, False]])

In [211]:
filedata[filedata > 20]

array([ 234, 2434,  354, 2323,   34, 1212,  122,  222])

In [212]:
# You can index with a list in numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [213]:
np.any(filedata > 20, axis = 0)
# which columns have at least ony value greater than 20

array([False,  True,  True,  True, False])

In [214]:
np.all(filedata > 20, axis = 0)
# which columns have all values greater than 20

array([False, False, False, False, False])

In [215]:
((filedata > 50) & (filedata < 1000))

array([[False,  True, False, False, False],
       [False,  True, False, False, False],
       [False, False, False, False, False],
       [False, False,  True,  True, False]])

#### Exercise time

In [216]:
m = np.array(([range(1,6)],[range(6,11)]))
print(m)
# you could do this and add all lines until 30

[[[ 1  2  3  4  5]]

 [[ 6  7  8  9 10]]]


In [217]:
# however, it is better to: 
n = np.array([range(1,31)]).reshape([6,5])
print(n)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [218]:
n[1:4,0:3]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [219]:
n[ [0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [220]:
# Option 1 (INCORRECT)
n[[0,0,4,4,5,5],[3,4,3,4,3,4]]

array([ 4,  5, 24, 25, 29, 30])

In [221]:
# Option 2 (CORRECT)
n[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [222]:
var = 10 
string = " helo " + str(var)

#### Some more linear algebra 

In [223]:
npA = np.array(range(0,8,2)).reshape(2,2)
print(npA)
npB = np.array(range(0,40,10)).reshape(2,2)
print(npB)

[[0 2]
 [4 6]]
[[ 0 10]
 [20 30]]


In [224]:
# Value by value multiplication
npC = npA * npB
print(npC)

[[  0  20]
 [ 80 180]]


In [225]:
# Element by element exponents
npD = npA ** 2
npE = np.power(npA, 3)
print(npD)
print(npE)

[[ 0  4]
 [16 36]]
[[  0   8]
 [ 64 216]]


In [226]:
# Matrix multiplication!
npF = npA @ npB
print(npF)

# alternatively 
npF_bis = np.matmul(npA, npB)
print(npF_bis)

# alternatively (NOT RECOMMENDED)
npF_bisbis = npA.dot(npB)
print(npF_bisbis)

[[ 40  60]
 [120 220]]
[[ 40  60]
 [120 220]]
[[ 40  60]
 [120 220]]


In [227]:
# Determinant 
detA = np.linalg.det(npA)
print(detA)

-7.999999999999998


In [228]:
# Transpose
trasA = np.transpose(npA)
print(trasA)

[[0 4]
 [2 6]]


In [229]:
# Inverse
invA = np.linalg.inv(npA)
print(invA)

[[-0.75  0.25]
 [ 0.5   0.  ]]
